import { chromium } from 'playwright';
import { spawn } from 'node:child_process';
import { mkdtempSync,mkdirSync,writeFileSync,readFileSync } from 'node:fs';
import { resolve } from 'node:path';
import { randomBytes } from 'node:crypto';
import assert from 'node:assert/strict';
import { commentsWorkbook } from '../server/excel.js';
const dir=mkdtempSync(resolve('data','ui-v2-')),port=14312,base=`http://127.0.0.1:${port}`,token=randomBytes(32).toString('hex'),password=randomBytes(24).toString('base64url'),docker=process.argv.includes('--docker');
let logs='';const child=docker?spawn('docker',['run','--rm','--init','--name','marshrut-ui-test','-p',`127.0.0.1:${port}:4310`,'-e',`PUBLIC_URL=${base}`,'-e',`SETUP_TOKEN=${token}`,'-e','CONTEST_DATA_DIR=/tmp/giveaway-test','--mount',`type=bind,source=${resolve('server')},target=/app/server,readonly`,'--mount',`type=bind,source=${resolve('public')},target=/app/public,readonly`,'contest-marshrut-postroen-giveaway'],{stdio:['ignore','pipe','pipe'],windowsHide:true}):spawn(process.execPath,['server/index.js'],{env:{...process.env,PORT:String(port),HOST:'127.0.0.1',PUBLIC_URL:base,CONTEST_DATA_DIR:dir,SETUP_TOKEN:token,ADMIN_PASSWORD_HASH:'',NODE_ENV:'test',AUTH_DISABLED:'false'},stdio:['ignore','pipe','pipe'],windowsHide:true});child.stderr.on('data',x=>logs+=x);child.stdout.on('data',x=>logs+=x);
let browser;try{
  for(let i=0;i<600;i++){try{if((await fetch(base+'/healthz')).ok)break;}catch{}await new Promise(r=>setTimeout(r,50));}
  assert.equal((await fetch(base+'/api/contests')).status,401);
  browser=await chromium.launch({channel:'chrome',headless:true});const context=await browser.newContext({viewport:{width:1440,height:1050},acceptDownloads:true,permissions:['clipboard-read','clipboard-write']});const page=await context.newPage(),errors=[];page.on('pageerror',e=>errors.push(e.message));
  await page.goto(base+'/#setup='+token);await page.getByRole('heading',{name:'Создайте пароль'}).waitFor();await page.locator('input[name=password]').fill(password);await page.getByRole('button',{name:'Сохранить пароль и войти'}).click();await page.getByRole('heading',{name:'НАЧНЁМ С РИЛСА.'}).waitFor();
  assert.equal(await page.locator('.side-nav button').count(),3);await page.evaluate(()=>document.fonts.ready);await page.screenshot({path:'artifacts/v2-new.png',fullPage:true,animations:'disabled'});
  const rows=Array.from({length:12},(_,i)=>({id:String(i+1),username:'test_guest_'+i,text:i?'Арт-зона, фудкорт, dj сеты @friend':'Плед зона → фудкорт → концееерт с @friend\nЖду праздник ❤️'}));rows.push({id:'99',username:'test_guest_0',text:'Ещё один комментарий'});rows.push({id:'100',username:'marshrut_postroen.media',text:'Правила конкурса'});
  // Collection is covered with a live reel and a virtualized DOM separately.
  await page.route('**/collect',route=>route.fulfill({status:202,contentType:'application/json',body:JSON.stringify({status:'paused',count:0,message:'Тестовая выгрузка'})}));
  await page.getByRole('textbox',{name:'Укажите ссылку на рилс'}).fill('https://www.instagram.com/reel/Dcv1u1Jo1QE/');await page.getByRole('button',{name:'Продолжить',exact:true}).click();await page.getByRole('heading',{name:'Комментарии из рилса'}).waitFor();
  const source=resolve('artifacts/ui-source.json');writeFileSync(source,JSON.stringify({comments:rows}));await page.locator('#source-file').setInputFiles(source);await page.getByText('14 комментариев собрано',{exact:true}).waitFor();
  const dl=page.waitForEvent('download');await page.getByRole('link',{name:'Скачать Excel со всеми комментариями'}).click();await (await dl).saveAs('artifacts/v2-all-comments.xlsx');
  await page.locator('#conditions').fill('Один аккаунт — один комментарий. Назвать три локации и отметить друга. Локации: арт-зона, DJ-сеты, фудкорт, концерт, плед-зона. Поставить лайк.');await page.getByRole('button',{name:'Создать промпт'}).click();await page.locator('#generated-prompt').waitFor();const first=await page.locator('#generated-prompt').inputValue();
  await page.locator('#conditions').fill('Написать любимую песню. Отметить друга. Подписаться на медиагид.');await page.getByRole('button',{name:'Создать промпт'}).click();await page.waitForFunction(()=>document.querySelector('#generated-prompt')?.value.includes('Написать любимую песню.'));const second=await page.locator('#generated-prompt').inputValue();assert.notEqual(first,second);
  await page.getByRole('button',{name:'Копировать',exact:true}).click();assert.equal((await page.evaluate(()=>navigator.clipboard.readText())).replaceAll('\r\n','\n'),second);await page.screenshot({path:'artifacts/v2-prompt.png',fullPage:true,animations:'disabled'});
  // Represents the manager-approved AI result. Preserve the source text verbatim.
  const selected=resolve('artifacts/ui-selected.xlsx');writeFileSync(selected,await commentsWorkbook(rows.slice(1,12)));await page.locator('#selection-file').setInputFiles(selected);await page.getByRole('heading',{name:'Участники отобраны'}).waitFor();
  await page.locator('[name=name]').fill('Репетиция · проверка нового интерфейса');await page.locator('[name=winnerCount]').fill('2');await page.locator('[name=reserveCount]').fill('1');await page.locator('[name=manualChecks]').fill('Проверить подписку по скриншоту.');await page.locator('[name=acknowledged]').check();await page.screenshot({path:'artifacts/v2-selected.png',fullPage:true,animations:'disabled'});
  await page.getByRole('button',{name:'К розыгрышу'}).click();await page.locator('.stage').waitFor();const video=page.waitForEvent('download',{timeout:90000});await page.getByRole('button',{name:'Снять видео и выбрать всех'}).click();
  await page.waitForTimeout(4000);await page.screenshot({path:'artifacts/v2-drawing.png',animations:'disabled'});await (await video).saveAs('artifacts/v2-rehearsal.webm');await page.getByRole('button',{name:'Закрыть розыгрыш'}).click();await page.getByRole('heading',{name:/Основные победители/}).waitFor();
  assert.equal(await page.locator('.result-card').count(),3);assert.equal(await page.locator('.result-card.reserve').count(),1);await page.locator('.result-card').first().click();await page.locator('[name=status]').selectOption('confirmed');await page.locator('[name=verified]').check();await page.getByRole('button',{name:'Сохранить проверку'}).click();await page.getByText('Подтверждён',{exact:true}).waitFor();
  await page.screenshot({path:'artifacts/v2-results.png',fullPage:true,animations:'disabled'});
  const session=await page.evaluate(()=>fetch('/api/session').then(r=>r.json()));const contests=await page.evaluate(()=>fetch('/api/contests').then(r=>r.json()));const id=contests[0].id;
  const audit=await page.evaluate(id=>fetch('/api/contests/'+id+'/export/audit').then(r=>r.json()),id);writeFileSync('artifacts/v2-audit.json',JSON.stringify(audit,null,2));assert.equal(new Set(audit.draw.results.map(x=>x.username)).size,3);
  const unauthorized=await fetch(base+'/api/contests/'+id+'/export/comments.xlsx');assert.equal(unauthorized.status,401);
  const csrf=await page.evaluate(async id=>{const r=await fetch('/api/contests/'+id+'/draw',{method:'POST',headers:{'Content-Type':'application/json','X-CSRF-Token':'wrong'},body:JSON.stringify({expectedRank:1})});return r.status;},id);assert.equal(csrf,403);
  await page.getByRole('button',{name:'Прошедшие конкурсы',exact:true}).click();await page.locator('.history-card').waitFor();await page.getByRole('button',{name:'Инструкция',exact:true}).click();await page.locator('.instructions article').first().waitFor();assert.equal(await page.locator('.instructions article').count(),7);
  await page.setViewportSize({width:390,height:844});await page.screenshot({path:'artifacts/v2-mobile.png',fullPage:true,animations:'disabled'});assert(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth));
  await page.getByRole('button',{name:/admin/}).click();await page.getByRole('heading',{name:'Войти в сервис'}).waitFor();await page.locator('input[name=password]').fill('incorrect');await page.getByRole('button',{name:'Войти',exact:true}).click();await page.locator('#login-error').filter({hasText:'Неверный'}).waitFor();await page.locator('input[name=password]').fill(password);await page.getByRole('button',{name:'Войти',exact:true}).click();await page.getByRole('heading',{name:'НАЧНЁМ С РИЛСА.'}).waitFor();
  assert.deepEqual(errors,[]);writeFileSync('artifacts/v2-browser-checks.json',JSON.stringify({passed:true,places:3,primary:2,reserve:1,sourceRows:14,selectedRows:11,consoleErrors:errors},null,2));console.log('Browser workflow passed: login, XLSX, regenerated prompt, selection, 2+1 draw, video, reviews, archive, mobile, logout.');
}catch(error){console.error(logs);throw error;}finally{await browser?.close();if(docker)await new Promise(resolve=>spawn('docker',['stop','marshrut-ui-test'],{stdio:'ignore',windowsHide:true}).on('exit',resolve));else child.kill();}
