import { chromium } from 'playwright';
import { spawn } from 'node:child_process';
import { mkdtempSync,mkdirSync,writeFileSync,readFileSync } from 'node:fs';
import { resolve } from 'node:path';
import { randomBytes } from 'node:crypto';
import assert from 'node:assert/strict';
import { commentsWorkbook } from '../server/excel.js';
import ExcelJS from 'exceljs';
import {readSourceWorkbook} from '../server/excel.js';
const dir=mkdtempSync(resolve('data','ui-v2-')),port=14312,base=`http://127.0.0.1:${port}`,token=randomBytes(32).toString('hex'),password=randomBytes(24).toString('base64url'),docker=process.argv.includes('--docker');
let logs='';const child=docker?spawn('docker',['run','--rm','--init','--name','marshrut-ui-test','-p',`127.0.0.1:${port}:4310`,'-e',`PUBLIC_URL=${base}`,'-e',`SETUP_TOKEN=${token}`,'-e','CONTEST_DATA_DIR=/tmp/giveaway-test','--mount',`type=bind,source=${resolve('server')},target=/app/server,readonly`,'--mount',`type=bind,source=${resolve('public')},target=/app/public,readonly`,'contest-marshrut-postroen-giveaway'],{stdio:['ignore','pipe','pipe'],windowsHide:true}):spawn(process.execPath,['server/index.js'],{env:{...process.env,PORT:String(port),HOST:'127.0.0.1',PUBLIC_URL:base,CONTEST_DATA_DIR:dir,SETUP_TOKEN:token,ADMIN_PASSWORD_HASH:'',NODE_ENV:'test',AUTH_DISABLED:'false'},stdio:['ignore','pipe','pipe'],windowsHide:true});child.stderr.on('data',x=>logs+=x);child.stdout.on('data',x=>logs+=x);
let browser;try{
  for(let i=0;i<600;i++){try{if((await fetch(base+'/healthz')).ok)break;}catch{}await new Promise(r=>setTimeout(r,50));}
  assert.equal((await fetch(base+'/api/contests')).status,401);
  browser=await chromium.launch({channel:'chrome',headless:true});const context=await browser.newContext({viewport:{width:1440,height:1050},acceptDownloads:true,permissions:['clipboard-read','clipboard-write']});const page=await context.newPage(),errors=[],requests=[];page.on('pageerror',e=>errors.push(e.message));page.on('request',r=>requests.push(r.url()));
  await page.goto(base+'/#setup='+token);await page.getByRole('heading',{name:'Создайте пароль'}).waitFor();await page.locator('input[name=password]').fill(password);await page.getByRole('button',{name:'Сохранить пароль и войти'}).click();await page.getByRole('heading',{name:'НАЧНЁМ С РИЛСА.'}).waitFor();
  assert.equal(await page.locator('.side-nav button').count(),3);await page.evaluate(()=>document.fonts.ready);await page.screenshot({path:'artifacts/v3-new.png',fullPage:true,animations:'disabled'});
  let source=process.argv.includes('--source')?resolve(process.argv[process.argv.indexOf('--source')+1]):resolve('artifacts/ui-source.xlsx');
  if(!process.argv.includes('--source')){const book=new ExcelJS.Workbook(),sheet=book.addWorksheet('Comments');sheet.addRow(['ID','Имя пользователя','URL профиля','Верифицирован','Текст комментария','Лайки','Дата','Ответ','ID родителя']);for(let i=0;i<343;i++)sheet.addRow([String(i),'test_guest_'+(i%273),'',false,'  Арт-зона → фудкорт → dj сеты @friend\n❤️ '+i+'  ',0,'','Нет','']);await book.xlsx.writeFile(source);}
  const rows=(await readSourceWorkbook(readFileSync(source))).rows;assert.equal(rows.length,343);
  await page.getByRole('textbox',{name:'Укажите ссылку на рилс'}).fill('https://www.instagram.com/reel/Dcv1u1Jo1QE/');await page.getByRole('button',{name:'Продолжить',exact:true}).click();await page.getByRole('heading',{name:'Исходный Excel',exact:true}).waitFor();
  assert.equal(await page.locator('#conditions').count(),0);await page.screenshot({path:'artifacts/v3-upload.png',fullPage:true});
  await page.locator('#source-file').setInputFiles(source);await page.getByText('343 комментариев загружено',{exact:true}).waitFor();await page.getByText('273 аккаунтов · все строки без отбора',{exact:true}).waitFor();
  const dl=page.waitForEvent('download');await page.getByRole('link',{name:'Скачать Excel для ИИ'}).click();await (await dl).saveAs('artifacts/v3-all-comments.xlsx');
  const outputBook=new ExcelJS.Workbook();await outputBook.xlsx.readFile('artifacts/v3-all-comments.xlsx');assert.equal(outputBook.worksheets.length,1);assert.equal(outputBook.worksheets[0].columnCount,2);assert.deepEqual((await readSourceWorkbook(readFileSync('artifacts/v3-all-comments.xlsx'))).rows,rows);
  await page.locator('summary').filter({hasText:'Посмотреть исходные комментарии'}).click();await page.getByLabel('Поиск исходных комментариев').fill(rows[0].username);assert.equal(await page.locator('[data-table=source] tbody tr').count(),rows.filter(r=>(r.username+' '+r.text).includes(rows[0].username)).length);await page.getByLabel('Поиск исходных комментариев').fill('');await page.locator('[data-table=source] [data-action=next]').click();await page.locator('[data-table=source] .pagination').filter({hasText:'2 / 14'}).waitFor();await page.locator('summary').filter({hasText:'Посмотреть исходные комментарии'}).click();
  const invalid=resolve('artifacts/ui-invalid.xlsx');writeFileSync(invalid,'Not Excel');await page.locator('#source-file').setInputFiles(invalid);await page.locator('#toast').filter({hasText:'корректный Excel'}).waitFor();assert.equal(await page.getByText('343 комментариев загружено',{exact:true}).count(),1);
  await page.screenshot({path:'artifacts/v3-source.png',fullPage:true});await page.setViewportSize({width:390,height:844});assert(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth));await page.screenshot({path:'artifacts/v3-source-mobile.png',fullPage:true});await page.setViewportSize({width:1440,height:1050});
  await page.locator('#conditions').fill('Один аккаунт — один комментарий. Назвать три локации и отметить друга. Локации: арт-зона, DJ-сеты, фудкорт, концерт, плед-зона. Поставить лайк.');await page.getByRole('button',{name:'Создать промпт'}).click();await page.locator('#generated-prompt').waitFor();const first=await page.locator('#generated-prompt').inputValue();
  await page.locator('#conditions').fill('Написать любимую песню. Отметить друга. Подписаться на медиагид.');await page.getByRole('button',{name:'Создать промпт'}).click();await page.waitForFunction(()=>document.querySelector('#generated-prompt')?.value.includes('Написать любимую песню.'));const second=await page.locator('#generated-prompt').inputValue();assert.notEqual(first,second);
  await page.getByRole('button',{name:'Копировать',exact:true}).click();assert.equal((await page.evaluate(()=>navigator.clipboard.readText())).replaceAll('\r\n','\n'),second);await page.screenshot({path:'artifacts/v3-prompt.png',fullPage:true,animations:'disabled'});
  // Represents the manager-approved AI result. Preserve the source text verbatim.
  const selectedRows=[...new Map(rows.map(r=>[r.username,r])).values()].slice(0,12);const selected=resolve('artifacts/ui-selected.xlsx');writeFileSync(selected,await commentsWorkbook(selectedRows));await page.locator('#selection-file').setInputFiles(selected);await page.getByRole('heading',{name:'Участники отобраны'}).waitFor();
  // Replacing source clears the previous selection and prompt, but retains rules.
  await page.locator('.completed-step>summary').first().click();await page.locator('#source-file').setInputFiles(source);await page.getByRole('heading',{name:'ОТ КОММЕНТАРИЯ — К ШАНСУ.'}).waitFor();assert.equal(await page.locator('#generated-prompt').count(),0);assert.equal(await page.locator('#selection-file').count(),0);assert.equal(await page.locator('#conditions').inputValue(),'Написать любимую песню. Отметить друга. Подписаться на медиагид.');
  await page.getByRole('button',{name:'Создать промпт'}).click();await page.locator('#selection-file').waitFor({state:'attached'});await page.locator('#selection-file').setInputFiles(selected);await page.getByRole('heading',{name:'Участники отобраны'}).waitFor();
  await page.locator('[name=name]').fill('Репетиция · проверка нового интерфейса');await page.locator('[name=winnerCount]').fill('2');await page.locator('[name=reserveCount]').fill('1');await page.locator('[name=manualChecks]').fill('Проверить подписку по скриншоту.');await page.locator('[name=acknowledged]').check();await page.screenshot({path:'artifacts/v3-selected.png',fullPage:true,animations:'disabled'});
  await page.getByRole('button',{name:'К розыгрышу'}).click();await page.locator('.stage').waitFor();const video=page.waitForEvent('download',{timeout:90000});await page.getByRole('button',{name:'Снять видео и выбрать всех'}).click();
  await page.waitForTimeout(4000);await page.screenshot({path:'artifacts/v3-drawing.png',animations:'disabled'});await (await video).saveAs('artifacts/v3-rehearsal.webm');await page.getByRole('button',{name:'Закрыть розыгрыш'}).click();await page.getByRole('heading',{name:/Основные победители/}).waitFor();
  assert.equal(await page.locator('.result-card').count(),3);assert.equal(await page.locator('.result-card.reserve').count(),1);await page.locator('.result-card').first().click();await page.locator('[name=status]').selectOption('confirmed');await page.locator('[name=verified]').check();await page.getByRole('button',{name:'Сохранить проверку'}).click();await page.getByText('Подтверждён',{exact:true}).waitFor();
  await page.screenshot({path:'artifacts/v3-results.png',fullPage:true,animations:'disabled'});
  const session=await page.evaluate(()=>fetch('/api/session').then(r=>r.json()));const contests=await page.evaluate(()=>fetch('/api/contests').then(r=>r.json()));const id=contests[0].id;
  const audit=await page.evaluate(id=>fetch('/api/contests/'+id+'/export/audit').then(r=>r.json()),id);writeFileSync('artifacts/v3-audit.json',JSON.stringify(audit,null,2));assert.equal(new Set(audit.draw.results.map(x=>x.username)).size,3);
  const unauthorized=await fetch(base+'/api/contests/'+id+'/export/comments.xlsx');assert.equal(unauthorized.status,401);
  const csrf=await page.evaluate(async id=>{const r=await fetch('/api/contests/'+id+'/draw',{method:'POST',headers:{'Content-Type':'application/json','X-CSRF-Token':'wrong'},body:JSON.stringify({expectedRank:1})});return r.status;},id);assert.equal(csrf,403);
  await page.locator('summary').filter({hasText:'Исходные комментарии'}).click();await page.getByLabel('Поиск исходных комментариев').fill(rows[0].username);assert.equal(await page.locator('[data-table=selected] tbody tr').count(),12);await page.getByRole('button',{name:'Прошедшие конкурсы',exact:true}).click();await page.locator('.history-card').waitFor();assert.equal(await page.locator('.history-winners .reserve').count(),1);await page.screenshot({path:'artifacts/v3-archive.png',fullPage:true});await page.getByRole('button',{name:'Инструкция',exact:true}).click();await page.locator('.instructions article').first().waitFor();assert.equal(await page.locator('.instructions article').count(),7);assert(!/Продолжить сбор|Открыть Instagram|Показать Chrome/.test(await page.locator('.page-content').innerText()));
  await page.setViewportSize({width:390,height:844});await page.screenshot({path:'artifacts/v3-mobile.png',fullPage:true,animations:'disabled'});assert(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth));
  await page.getByRole('button',{name:/admin/}).click();await page.getByRole('heading',{name:'Войти в сервис'}).waitFor();await page.locator('input[name=password]').fill('incorrect');await page.getByRole('button',{name:'Войти',exact:true}).click();await page.locator('#login-error').filter({hasText:'Неверный'}).waitFor();await page.locator('input[name=password]').fill(password);await page.getByRole('button',{name:'Войти',exact:true}).click();await page.getByRole('heading',{name:'НАЧНЁМ С РИЛСА.'}).waitFor();
  assert(requests.every(url=>new URL(url).origin===base),'The app must not request Instagram or a collector');assert.deepEqual(errors,[]);writeFileSync('artifacts/v3-browser-checks.json',JSON.stringify({passed:true,places:3,primary:2,reserve:1,sourceRows:rows.length,selectedRows:selectedRows.length,consoleErrors:errors},null,2));console.log('Browser workflow passed: login, XLSX, regenerated prompt, selection, 2+1 draw, video, reviews, archive, mobile, logout.');
}catch(error){console.error(logs);throw error;}finally{await browser?.close();if(docker)await new Promise(resolve=>spawn('docker',['stop','marshrut-ui-test'],{stdio:'ignore',windowsHide:true}).on('exit',resolve));else child.kill();}
